### ISSUE TITLE
Accessing Web Interface from Mobile Device / iPad / iPhone shows wrong information

### ISSUE THREAD

**Issue by arretx** [omersiar/esp-rfid#302] opened 2019-08-28 19:49 UTC
Okay, this one is blowing my mind.

I have two iMacs sitting next to each other.  When I visit the web interface of the lock system (192.168.5.61) on  both of those computers, I see my configuration settings, users, etc.

If I try to access the same IP inside of the network on any iOS mobile device in either Chrome or Safari, the interface appears as though it hasn't been setup yet.  It has the fallback network settings, no users, no logs...and it doesn't respond to input when testing the relay.

My Android device seems to work, however.

What's the deal with iOS devices?

**Comment by proddy** [comment] 2019-09-06 06:38
I've seen this too, on iOS with Chrome. Firefox and Safari. Looks like the websockets is not working and no data is sent back to the mobile device. Although it works fine when you simulate an iPhone on a desktop (eg. using Chrome with dev tools & device simulation).  Doesn't happen on Android phones so expect its something in iOS blocking it, perhaps in the latest iOS update. I'm looking into the root cause as it did work before right?

**Comment by fabiradi** [comment] 2019-09-08 20:28
## :bulb: TL;DR:

**Use Chrome or Firefox on Mac OS.** For iOS, I could not find a workaround.

## What happens?

In Safari/Mac (10.14.6 Mojave), the console has the following error:

> [Error] WebSocket connection to 'ws://192.168.188.73/ws' failed: Unexpected response code: 401 Unauthorized

After that, no other settings/values are present from the websocket, so all displayed values seem to be "default".

### The problem is:

- There is **no error handling**, if the websocket does not work as expected (or looses connection).
- **You can still use the GUI**, because it already has *default values* loaded. You can even set all the values, save them, and (pretend) to reboot.
- **After reloading, nothing has changed** (because nothing was saved and the websocket still has a 401 error) – I did that twice 🤦‍♂

### :rotating_light: It does NOT work on these browsers:

- Mac OS (10.14.6 Mojave)
  - Safari 12.1.2
- iOS (iPad 12.1.4 / iPhone 13.1 public beta 2)
  - Safari
  - Chrome

### :white_check_mark: It DOES work in these browsers:

- Mac OS (10.14.6 Mojave)
  - Chrome 76
  - Firefox 69

## :man_shrugging: Next steps?

- Is there a version of iOS or Mac OS + Safari, that it has ever worked on?
- Has anything changed in the web UI lately, that may cause this error?
- Can the UI send an authentication header or does the browser handle this automatically?

**Comment by fabiradi** [comment] 2019-09-09 06:00
### :mag: Further Investigation

- The problem is not new, see #165 **Websocket broken in version 0.8.2**
- Using a (specific) **fixed version 1.1.0 of "ESP Async WebServer"** seems to fix the issue, see #167 --> I have NOT verified this!
- I have compared version 1.1.0 commit against the master branch, but could not find any obvious reason for the changed behavior of ESPAsyncWebserver.
- The **change is reversed** by [Commit 437f23 "onWsEvent() improved"](https://github.com/esprfid/esp-rfid/commit/437f23cf826fdea48c9ed798b7c7a3a27c911b62)
- There is a **similar issue in ESPurna**: [Web Interface not working on Safari/iOS](https://github.com/xoseperez/espurna/issues/507)
- ESPAsyncWebserver might also have a [Bug in basic authentication #575](https://github.com/me-no-dev/ESPAsyncWebServer/issues/575).

### :bulb: Other workarounds

- **Safari has a [bug with websockets and basic authentication](https://bugs.webkit.org/show_bug.cgi?id=80362)**: Send username/password together with websocket request might be an (unsafe) workaround? See https://stackoverflow.com/a/41521871

## :man_shrugging: Next steps?

> **Note:** I have *not* set up the project in PlatformIO, yet. 

- Add `websock.onerror(...)` in [esprfid.js](https://github.com/esprfid/esp-rfid/blob/stable/src/websrc/js/esprfid.js#L1347) to track down the error?
- Try version 1.1.0 of ESPAsyncWebserver (see #167)

**Comment by omersiar** [comment] 2019-09-09 08:41
@fabiradi Thank you for the Insightful (and colorful) investigation. Mos-def help.

**Comment by proddy** [comment] 2019-10-23 18:05
@fabiradi @omersiar has there been any further progress here? Need any help?

**Comment by fabiradi** [comment] 2019-10-27 21:17
> @fabiradi @omersiar has there been any further progress here? Need any help?

Sorry, haven't had time to take a deep look at it. I will have to postpone it at least 3-4 weeks.

**Comment by nickbardom** [comment] 2020-10-18 17:55
Any news about that? I notice the first login after a factory restore works and we can even change the parameters and it is saved and reboot, after the reboot, the websocket does not work anymore. Maybe a bug in the config file?

**Comment by matjack1** [comment] 2022-03-18 17:22
Hey @fabiradi @arretx @proddy if you are still interested with this, could you please try again with the latest `dev` branch?

I'm able to help here to fix this issue. Thank you very much for all the research you've done, but unfortunately I don't have a mobile Apple device at hand to test this, so I need your help here a bit more :(

**Comment by matjack1** [comment] 2022-04-01 11:15
I'm closing this as it's reported to be working here: https://github.com/esprfid/esp-rfid/issues/370#issuecomment-1085748230 but please reopen if necessary.

**Closed as completed by matjack1** 2022-04-01 11:15 UTC
Labels: bug, need_confirmation, Web UI
