### ISSUE TITLE
Web browser compatibility(Safari)

### ISSUE THREAD

**Issue by nickbardom** [omersiar/esp-rfid#397] opened 2020-08-22 23:09 UTC
Hello,

When using with Iphone (Safari web browser) it is not possible to save the changes. Is there any workarounds to solve this?

**Comment by Tinker-Bel** [comment] 2020-09-06 18:23
Hello, I've experienced the same problem!

**Comment by nickbardom** [comment] 2020-09-27 16:15
So far I tried a lot of things in the code, but I still can't make it work with Safari.

**Comment by nickbardom** [comment] 2020-10-18 17:57
Any news about that? I notice the first login after a factory restore works and we can even change the parameters and it is saved and reboot, after the reboot, the websocket does not work anymore. Maybe a bug in the config file?

**Comment by moritzj29** [comment] 2021-02-13 10:21
I'm experiencing the same issue. First log-in works with Safari (macOS, iOS). Changing WiFi to client mode. Afterwards status is no longer shown, logs are not shown, ... in **Safari**. 

**Firefox works**.

Maybe this related to a bug in Safari: https://bugs.webkit.org/show_bug.cgi?id=80362 (open since 9 years, so I won't hope for a fix...)
Apparently, Safari does not support Basic Auth for web socket.

**Comment by nickbardom** [comment] 2021-02-20 18:04
> 
> 
> I'm experiencing the same issue. First log-in works with Safari (macOS, iOS). Changing WiFi to client mode. Afterwards status is no longer shown, logs are not shown, ... in **Safari**.
> 
> **Firefox works**.
> 
> Maybe this related to a bug in Safari: https://bugs.webkit.org/show_bug.cgi?id=80362 (open since 9 years, so I won't hope for a fix...)
> Apparently, Safari does not support Basic Auth for web socket.

That is exactly the problem I am having! Without fixing that, it is impossible to use it on Iphone or Ipad. I tried to find out how to disable the authentication in the source code, but I didn't find out a way. Did you manage to compile a code to work with Safari?

**Comment by moritzj29** [comment] 2021-02-21 13:34
I'm going with Firefox at the moment. For an access control system I want authentication to be in place, so disabling it is no option for me. Going to a different authentication mechanism (e.g. Cookie based) involves probably a lot of work...

**Comment by nickbardom** [comment] 2021-02-23 23:26
> 
> 
> I'm going with Firefox at the moment. For an access control system I want authentication to be in place, so disabling it is no option for me. Going to a different authentication mechanism (e.g. Cookie based) involves probably a lot of work...

Thanks for replying. Unfortunately on Iphone or Ipad, if you use Firefox, it will not work as it uses the Safari webkit... I was thinking about a way to disable authentication and use it as stand alone(as an access point). So the wifi login would be the authentication. Do you have any tips about compiling it without authentication?

**Comment by moritzj29** [comment] 2021-02-24 12:41
hmm I have not tried it myself, but it would start with this line:

https://github.com/esprfid/esp-rfid/blob/162a7fff662833154172f9defcf382c4be0b0336/src/config.esp#L115

commenting out this line should disable the authentication of the websocket.

since this problem is subject of several issues here and none of these references the others, let me cross-reference #412, #370, #353, #302

maybe lorol's fork of the ESPAsyncWebServer may be an option, since it allows cookies for authentication of the websocket connection.

**Comment by matjack1** [comment] 2022-03-18 17:11
Hey @nickbardom @moritzj29 and @Tinker-Bel if you are still interested in this, could you please try with the latest `dev` branch?

If you are still experiencing the problem let me know, I'm able to help here.

Can you reproduce only on Safari? I don't have an Apple mobile device to test this though :(

**Comment by Tinker-Bel** [comment] 2022-04-23 17:05
Hello,
I've tried with version 1.3.7 and now it seems to work!
After commiting and restarting, you have to be a little patient, but then it works.
I tested with an Iphone and Safari.

One difference with f.i. chrome: after you put in your password, you get a new screen with a username and password field.
On Chrome, on startup, I only get an password field, not a username field!

**Comment by matjack1** [comment] 2023-03-28 20:40
I'm closing this for now as I've tested the `dev` branch and it's all good on Chrome.

If this is not good, please reopen the issue

**Closed as completed by matjack1** 2023-03-28 20:40 UTC
Labels: bug, need_confirmation, Web UI
