### ISSUE TITLE
Can I add RTC clock synchronization NTP code and save the power down clock

### ISSUE THREAD

**Issue by vvvyky** [omersiar/esp-rfid#569] opened 2022-12-20 03:31 UTC
Can I add RTC clock synchronization NTP code and save the power down clock

**Comment by matjack1** [comment] 2022-12-20 20:23
Sure @vvvyky, that would be a good idea :)

**Comment by matjack1** [comment] 2024-01-16 16:36
I'm closing this as it's a duplicate of: https://github.com/esprfid/esp-rfid/issues/508

**Closed as completed by matjack1** 2024-01-16 16:36 UTC
Labels: enhancement, help wanted, hardware
