### ISSUE TITLE
Piccscan fills UID to all textfields in UI

### ISSUE THREAD

**Issue by iBobik** [omersiar/esp-rfid#166] opened 2018-10-19 00:46 UTC
When tag is read backend sends command puccscan to frontend. If UI have some textfield (e.g. HW config) it will fill tag UID there. It should do it only for textfield for UID in users section.

Happens there:
https://github.com/esprfid/esp-rfid/blob/stable/src/websrc/js/esprfid.js#L457

**Comment by omersiar** [comment] 2018-10-19 14:43
This not a bug but a feature :), ok actually it's an annoying bug but the text field for searching on FooTable does not have an id, so when web socket message is received javascript tries to find text-field on whole page.

**Comment by omersiar** [comment] 2018-11-11 20:43
This is fixed by 0112881

**Closed as completed** 2018-11-13 11:16 UTC
Labels: bug
