### ISSUE TITLE
stability problem after update to Build-163 and solution

### ISSUE THREAD

**Issue by stupsi099** [omersiar/esp-rfid#608] opened 2023-11-20 20:21 UTC
i update 5 Systems to generic build 163 and got same stability problems after update
(official 3x green Board, 2x blue Board)

if you log in it takes 5 second to update the status screen, if you go into any settings you will push back to status screen after a few second.

**Solution:**
update to build 163
factory reset ->  you will get an AP with esp-rfidXXXXX     (->XXX unique number<-)
login with 192.168.4.1 pw:admin and update again to build 163
factory reset again -> you will get an AP with esp-rfid  (->without number<-)
config manual (do not use your old config file!!!)
power off and restart - now my system works

if you import your user file - you have to edit and clear the pincode field again.
![grafik](https://github.com/esprfid/esp-rfid/assets/40528102/ebcfbfea-14bb-4e49-af08-7f7ca1494ef0)
![grafik](https://github.com/esprfid/esp-rfid/assets/40528102/d0113a4c-df68-4777-82ba-c56c0d8ba4ae)
because sometimes there are wrong data inside.

if i login to the reader the status info appear immediately.
not shure if you can skip some task above

br rupert

**Comment by matjack1** [comment] 2023-11-21 14:07
hello @stupsi099 thank you very much for testing the new version!

Can you please share your configuration file when it has problems? So that I can try reproducing your initial situation and see what's going on. Since you say that if you reset and start from scratch it works, I think it's a problem with your specific configuration that I have not tested yet.

If you prefer to share it via mail it's fine too.

**Comment by pvtex** [comment] 2024-06-08 14:55
pincode problematic should be fixed as in #641

**Comment by matjack1** [comment] 2024-06-11 16:36
This should be now fixed by #645 

Thank you @pvtex!

@stupsi099 if you want to try again a new build from `dev`, this should be fixed. I'm closing for now but if it's still there let me know.

**Closed as completed by matjack1** 2024-06-11 16:36 UTC
Labels: bug, confirmed
