### ISSUE TITLE
Access log is empty

### ISSUE THREAD

**Issue by clabnet** [omersiar/esp-rfid#325] opened 2019-10-08 19:58 UTC
Using version https://github.com/esprfid/esp-rfid/releases/tag/1.3.3, on NodeMCU Lolin and RFID reader RC522. 
All RFID cards are recognized correctly, but the access log is empty.

I am a developer, your code is of great quality.

**Comment by bigshit11elf** [comment] 2019-10-24 20:40
Same problem here. So far this behaviour is unfixable.

BTW: Hardware is Wemos D1 Mini and an RC522 reader.

**Comment by omersiar** [comment] 2019-11-06 07:47
There are some great changes since 1.3.3 by @frenchie7. So please, If you are willing to test these changes, I just released some test binaries which can be downloaded here:

https://github.com/esprfid/esp-rfid/releases/tag/1.3.5

Change log can be reviewed here:

https://github.com/esprfid/esp-rfid/blob/dev/CHANGELOG.md

**Comment by bigshit11elf** [comment] 2019-11-17 18:50
Using this firmware the following issues arise:

- Users / Access Log not accessible all the time
- something crashes when RFID is scanned > Users / Access Log not accessible after that
- scanned rfid is not transferred via mqtt

**Comment by frenchie71** [comment] 2020-01-08 14:59
Hi @bigshit11elf , could you please specify a couple of things in order for me to reproduce the issues:

**Users/Access Log not accessible all the time**

What is the symptom ? Does it hang ? How are you trying to access it ? Does the ESP reboot ? Can you define when it is accessible and when not (opening Event Log, then Access Log or opening one log while the other one loads etc.) ?

**Something crashes when RFID is scanned**

Which reader hardware ? All RFIDs ? Only Some ? Always ? Does the ESP reboot ? Do you reconnect to the Webpage after it crashes (because Socket connection will be lost if it reboots, that would be by design)?

**Scanned RFID not transmitted via MQTT**

Which MQTT topics are you listening to ? Have you set the mqtt logging option ?

Many thanks,

**Comment by sinclairfr** [comment] 2020-02-07 17:52
Hello,
 
On version 1.3.1 with :

- official board

- this reader : [https://www.aliexpress.com/item/32849941237.html?spm=a2g0s.9042311.0.0.27424c4dU0wP99](url)

I have the following bugs : 

- hang/freezing and sometimes reboot when trying to change an existing user.

- hang/freezing when reading a unknown rfid badge

- no access event or when there are event they are 1 or 2 days old

- occasional bug/freeze when trying to consult event or access logs

- random hang/freezing after a few hours

When I talk about freezing it is from the webpage but I also ping the board in order to be sure that is is not just another issue and there is no answer to the ping .

**Comment by matjack1** [comment] 2023-01-22 21:46
@clabnet @sinclairfr I'm not sure if you are still interested in this project, but this PR: https://github.com/esprfid/esp-rfid/pull/577 should fix a lot of the stability issues of the web interface.

I'm closing this issue for now, but let me know if you still have issues. Thank you!

**Closed as completed by matjack1** 2023-01-22 21:46 UTC
Labels: bug, need_confirmation, investigate

**Comment by clabnet** [comment] 2023-01-24 14:15
@sinclairfr I will try later, Thank's for tips,
