### ISSUE TITLE
Disconnected from MQTT server

### ISSUE THREAD

**Issue by js903801** [omersiar/esp-rfid#250] opened 2019-03-03 20:54 UTC
Hello, my original ESP RFID Relay board sporadically loses the connection to the MQTT server and does not reconnect automatically. Only after a reset is the MQTT will connect again. I read that I should use the version 0.8, here is the same problem. Just like the version 1.2. What can I do?

**Comment by omersiar** [comment] 2019-04-05 10:07
Can you please share mqtt logs?

**Comment by omersiar** [comment] 2019-04-05 10:40
MQTT Code should be revised. #256

**Comment by cyberhasse** [comment] 2019-05-18 16:16
Changing line:142 in main.cpp to unsigned long interval = 55; 
works for me!

Great work btw.
Regards.

**Comment by omersiar** [comment] 2019-05-18 16:23
Interesting, this shouldn't be problem unless there are some rate limits on the server side. Thank you for sharing

**Comment by moneybag** [comment] 2019-06-13 06:03
Can you provide a new bin file or update,  i dont have  platform io

**Comment by Marsx79** [comment] 2019-06-13 09:36
> Changing line:142 in main.cpp to unsigned long interval = 55;
> works for me!
> 
> Great work btw.
> Regards.

How can I adjust that? Is an Upadate planned? I also have the problem.

**Comment by cyberhasse** [comment] 2019-06-13 10:00
Compiling the dev version seems to fix the issue!
I can provide a bin file when i get home.

Regards.

**Comment by Marsx79** [comment] 2019-06-13 10:20
> Compiling the dev version seems to fix the issue!
> I can provide a bin file when i get home.
> 
> Regards.


That would be great. THX

**Comment by moneybag** [comment] 2019-06-13 12:53
thx

**Comment by cyberhasse** [comment] 2019-06-13 14:59
The bin file is here:
https://drive.google.com/file/d/1fJ6QaL5geuwFs9yN2COBUVS5Ai8Jo2dy/view?usp=sharing

I also added : SPI.setClockDivider(SPI_CLOCK_DIV8);
wich helps with longer cables.. mine is approx. 1m
Regards.

**Comment by moneybag** [comment] 2019-06-13 17:02
Thx, i flashed it successfully.
lets wait and see
edit: it works!
https://www.youtube.com/watch?v=yy6OEf5QdMQ

**Comment by LEJOUI** [comment] 2019-08-13 07:35
This solution worked for me. In v1.3.3 this problem was still there and caused a lot of mqtt disconnections.

**Comment by LEJOUI** [comment] 2019-08-13 20:51
Seems I was too early. Still having disconnected from mqtt after a few hours.

For now, I'm testing this solution in v1.3.3, coming back with results..

**Comment by cyberhasse** [comment] 2019-08-14 06:13
I bought a new router and after that the problem is better.
Regards.

**Comment by LEJOUI** [comment] 2019-08-14 21:44
Yes, still no luck over here.. It would be nice that after a drop in wifi or tcp disconnected there would be a few attempts to try to connect to the mqtt server again, or a setting that when tcp disconnects a restart will take place. For now my solution is to disable wifi after x minutes so it reconnects to my mqtt server again. Downside is that i've to scan the tag twice after a long time not in use.

**Comment by drthanwho** [comment] 2019-09-29 08:26
Also on v1.3.3 and I'm getting MQTT disconnected after a few hours. For now I've set it to reboot every 24 hours but still not a solution since it disconnects after 3 - 4 hours. 

Anyone worked any possible solution for this?
![image](https://user-images.githubusercontent.com/22405505/65874202-e5fd7e00-e38d-11e9-9b37-d68b7c115560.png)

**Comment by Hini2001** [comment] 2021-05-16 08:34
Hello and good Day to you All.
I have the Same Problem. I had esp rfid (actual ver 1.3.1) on a Node mcu and use it to control several Things over mqtt and IOBROKER. But After different time the mqtt Connection is closed. In the log file i could read:

WARN	mqtt	Disconnected from MQTT server
Additional Data	TCP_DISCONNECTED

No wlan issues and no wlan disconnections. Just the mqtt Connection is closing. Every other mqtt Client is still connected with the mqtt IOBROKER Server.
After a reboot of the esp rfid it establish the Connection again for sometimes hours or sometimes 1 Day... 
So i hope you can help me fixing this issue.

**Closed as completed** 2022-02-27 08:37 UTC
Labels: bug, confirmed
