### ISSUE TITLE
my problems growing

### ISSUE THREAD

**Issue by zefirpsaryanov** [omersiar/esp-rfid#382] opened 2020-05-29 17:51 UTC
![Screenshot_20200527_173603_com android chrome](https://user-images.githubusercontent.com/46773417/83289708-18e26500-a1ee-11ea-90b9-45a135671854.jpg)

**Comment by matjack1** [comment] 2022-03-30 20:17
Not sure what the problem is here, I'm closing for now, but please reopen if you need to!

**Closed as completed by matjack1** 2022-03-30 20:17 UTC
